### ISSUE TITLE
Crash when using batch converter using autoeq ParametricEQ

### ISSUE THREAD

**Issue by AndreaHasani** [ThePBone/DDCToolbox#1]
I'm getting a crash when the error "1865637 segmentation fault (core dumped)" when trying to convert a autoeq ParametricEQ to VDC.

I compiled this from source on arch linux 64bit

Thanks for this utility

**Comment by ThePBone** [comment]
Could you please provide me the AutoEQ parametric file, you tried to convert?

**Comment by ThePBone** [comment]
Since you haven't updated the issue after three weeks I suspect that you solved your issue.

Feel free to reopen it if you or someone else comes across this problem again. Please also upload the affected file in that case.

**Comment by ThePBone** [comment]
#3 probably solves this issue
