### ISSUE TITLE
Request: Add a preamp option

### ISSUE THREAD

**Issue by swan11jf** [ThePBone/DDCToolbox#2]
Hi, after using autoeq to export a parametric txt into ddc toolbox, this results in many frequencies with large negative gains (issue 170 in autoeq if you want more context).  Thus, would it be possible to add a preamp feature?

**Comment by ThePBone** [comment]
Hey, there is already an easy solution to do this. You can add a new filter of type 'Unity Gain' to your project and use it as a preamp. It will boost/attenuate all frequencies by x dB.

**Comment by swan11jf** [comment]
Oh, silly me - completely forgot about all the other filters. Thanks for your time and great software!

**Comment by ThePBone** [comment]
Thanks, no problem :D
