### ISSUE TITLE
Parametric EQ txt imports but doesn't show graph

### ISSUE THREAD

**Issue by swan11jf** [ThePBone/DDCToolbox#3]
I'm importing a parametric eq txt from autoeq with the following values:
Filter 1 ON PK Fc 22 Hz Gain -11.1 dB Q 0.78
Filter 2 ON PK Fc 55 Hz Gain -2.7 dB Q 1.37
Filter 3 ON PK Fc 2068 Hz Gain -2.8 dB Q 2.76
Filter 4 ON PK Fc 10066 Hz Gain -9.0 dB Q 4.04
Filter 5 ON PK Fc 20764 Hz Gain -2.4 dB Q 1.94
Filter 6 ON PK Fc 603 Hz Gain 2.9 dB Q 1.19
Filter 7 ON PK Fc 4848 Hz Gain -4.1 dB Q 2.48
Filter 8 ON PK Fc 7709 Hz Gain 2.5 dB Q 3.23
Filter 9 ON PK Fc 15498 Hz Gain -4.2 dB Q 4.40
Filter 10 ON PK Fc 22050 Hz Gain -2.4 dB Q 1.76

However, the graph doesn't appear, although other parametric txts seem to work. I've tried making a copy of this txt, although the program instantly crashes if I try and import it.

![image](https://user-images.githubusercontent.com/39700090/82499578-cb794000-9ae9-11ea-874d-9e60ebc9b82f.png)

**Comment by ThePBone** [comment]
Thanks for the detailed report.
The file you tried to import is missing colons in each line behind the 'Filter x' part and my parser was expecting those. (Maybe that file uses an older syntax). Nevertheless, that should never happen and I quickly rewrote the affected code to use a more 'flexible' regex matcher and better checks to prevent crashes (see commit 656b8e162caea7be2acca749d00a3a3e604a23c7).

You can download the latest nightly build from my server: <https://nightly.timschneeberger.me/ddctoolbox-win/ddctoolbox-win64_1.3.73.zip>

By the way, that nightly build has a lot of changes (the last stable release was 6 month ago 😅). Most interesting changes: phase response plot, new filters (including a fully customizable one) and direct AutoEQ integration

**Comment by swan11jf** [comment]
Thanks for you response - I've managed the import and export a vdc from the newest version. However, v4a instantly crashes if I try and select it - do you have any idea why? This issue has happened once before.

**Comment by ThePBone** [comment]
I've heard that Viper's convolver module is not really optimized for filter types other than 'Peaking', although it still seems to work most of the time. JamesDSP has a more advanced convolver and should work just fine.

Did it just stop processing or is the Viper app force closing when you try to load it? If it's the latter one, then it could be a bug in the V4A app, in that case you could try to get the error from the Android Logcat or send me the VDC that causes these errors.

**Comment by swan11jf** [comment]
Hi, please find attached the vdc file that causes the problem (just renamed .vdc to .txt so I could upload here)
[hd650.txt](https://github.com/ThePBone/DDCToolbox/files/4662447/hd650.txt)

This vdc came from me trying to get the sound profile of the HD650 on my bose quiet control 30. I believe a similar problem happened with trying to get the profile of the AKG 712. 

Here's also the irs of the HD650 which does work with v4a convolver: 
[hd650irs.zip](https://github.com/ThePBone/DDCToolbox/files/4662464/hd650irs.zip)

**Comment by ThePBone** [comment]
Alright, I found the problem. In the VDC file, there are some coefficients set to NaN, which is perfectly normal and should not cause any issues. The current V4A version tries to parse this value to a float and does not catch the exception if there was a conversion error. 

As a workaround you can replace those NaN (or nan) values with 0 for now. The upcoming V4A version will have this issue fixed.

**Comment by swan11jf** [comment]
Fantastic - thanks for your help. Are there any advantages to using the convoler over DDC and vice versa? Finally do you know where I can grab some proper documentation for this software - I've been using V4A and I still get mystified what some things actually do...

**Comment by ThePBone** [comment]
I don't know if there are any advantages, but using the convolver is a bit more battery-draining then VDCs and can introduce a tiny delay.

In V4A (version 2.7.1.6), you can long-press an effect and it'll pull up a bottom-sheet explaining all the parameters and the effect itself.
