### ISSUE TITLE
Program not responding when pressing search with empty field in "download from autoEQ"

### ISSUE THREAD

**Issue by basileus-sys** [ThePBone/DDCToolbox#7]
Just as the title says, if you search for something from autoEQ but you leave the field empty the program freezes.
![immagine](https://user-images.githubusercontent.com/52258368/123137577-631b3180-d454-11eb-944d-781810146de4.png)

**Comment by ThePBone** [comment]
Hey, you can try out the latest beta version. Windows beta binaries are available here: https://nightly.timschneeberger.me/ddctoolbox-win/

I recently added a check that makes sure that the search query is at least 3 characters long to fix this issue.
